import Head from 'next/head'
import Header from '@/components/Header/Header'
import About from './About/About'
import Skills from './Skills/Skills'
import Experience from './Experience/Experience'
import Projects from './Projects/Projects'

export default function Home() {
  return (
    <>
      <Head>
        <title>Porfolio - Rafael Saraiva</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.15.1/devicon.min.css" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <About />
      <Skills />
      <Experience />
      <Projects />
    </>
  )
}
