import Head from 'next/head'
import { Poppins } from 'next/font/google'
import Header from '@/components/Header/Header'
import About from './About/About'



export default function Home() {
  return (
    <>
      <Head>
        <title>Porfolio - Rafael Saraiva</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <About />

    </>
  )
}
